# Generated by Django 5.2.1 on 2025-06-23 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_category_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='max_participants',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
