# Generated by Django 5.2.1 on 2025-06-23 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_evento_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='event_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Event date and time'),
        ),
        migrations.AddField(
            model_name='evento',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Event location'),
        ),
    ]
