# Generated by Django 5.2.1 on 2025-06-23 21:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_evento_event_date_evento_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='event_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 7, 1, 12, 0), verbose_name='Event date and time'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='evento',
            name='location',
            field=models.CharField(default='Por definir', max_length=255, verbose_name='Event location'),
            preserve_default=False,
        ),
    ]
