# Generated by Django 5.2.1 on 2025-06-24 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_evento_event_date_alter_evento_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('offensive', 'Contenido ofensivo o lenguaje inapropiado'), ('discriminatory', 'Contenido discriminatorio (sexo, raza, religión, política, etc.)'), ('spam', 'Spam o publicidad no autorizada'), ('unrelated', 'Contenido no relacionado con la actividad'), ('false', 'Información falsa o engañosa'), ('violence', 'Incitación a la violencia o actividades ilegales')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.evento')),
                ('reporter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
