# Generated by Django 5.2.1 on 2025-06-24 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_eventreport'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventreport',
            name='description',
        ),
    ]
