# Generated by Django 5.2.1 on 2025-07-07 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_eventreport_event'),
        ('api', '0011_alter_customuser_username'),
    ]

    operations = [
    ]
