# Generated by Django 5.2.1 on 2025-07-08 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_merge_20250707_1741'),
        ('api', '0013_notification'),
    ]

    operations = [
    ]
