# Generated by Django 5.2.1 on 2025-07-22 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_actividad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('evento', 'Evento'), ('comentario', 'Comentario'), ('seguimiento', 'Seguimiento')], max_length=20),
        ),
    ]
