# Generated by Django 5.2.1 on 2025-07-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_eventoimagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventoimagen',
            name='url',
            field=models.URLField(max_length=1000),
        ),
    ]
