# Generated by Django 5.2.1 on 2025-07-24 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_remove_customuser_profile_picture_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
